### ISSUE TITLE
1.1.1 START (/HOME)

### ISSUE THREAD

**Issue by FireRay** [FireRay/report-bug-work#22]
![image](https://user-images.githubusercontent.com/22036343/65591975-e7920500-df8d-11e9-8ecf-e2ce6251b48e.png)

![image](https://user-images.githubusercontent.com/22036343/65592071-1f994800-df8e-11e9-84d4-d070193a64ee.png)

![image](https://user-images.githubusercontent.com/22036343/65591784-72becb00-df8d-11e9-8bfe-94d793095ef6.png)

![image](https://user-images.githubusercontent.com/22036343/65592131-46f01500-df8e-11e9-9f89-b329471039c7.png)

Vid start sökningen så kommer artiklar upp som även tillhör andra klasser. 

Testad som admin/inloggad student och ej inloggad på samtliga sidor. 

Task: Om jag som Admin/student eller utloggad går in på startsidan så skall det bara finnas dom tillhörande klass artiklar visade. 

Funktionslistan Start (/home)

Endast artiklar som är publicerade för klassen/hemsidan man är inne på skall listas i sökresultatet

**Comment by void00** [comment]
Dom klassernas artiklar delas av olika klasser och ska inte exluderas eftersom dom till hör klassen som "äger" domänen. Tror "Funktionslistan" har syftingsfel.

**Comment by FireRay** [comment]
Samtal m Dennis, missförstånd från min sida.
